### PR TITLE
some type fixes

### PR DESCRIPTION
**Pull request by mildsunrise**
this PR first makes setTargetBitrateAsync consistent with setTargetBitrate,
~~and then factors out most of the logic (common to both) to a new private function called `__setTargetBitrate`.~~

~~to do this, we move the call to `getActiveLayers` (or `getActiveLayersAsync`) up in the function, which could have small side effects. please see the commit message for more info~~

### CODE REVIEW

**Comment by mildsunrise** [comment]
oh, but we're still using it in StreamView, aren't we? and I thought we wanted to avoid blocking the event loop so frequently

**Comment by murillo128** [comment]
I mean to keep only the async version

**Comment by mildsunrise** [comment]
ah sorry, misread. I'm perfectly okay with it, I'll replace the last commit

**Comment by mildsunrise** [comment]
it is done

**Comment by mildsunrise** [comment]
tests are failing after swapping `setTargetBitrate` for `setTargetBitrateAsync`, and I'm a little puzzled why...

**Review by murillo128 — APPROVED** [review]
lgtm

**Review by murillo128 — APPROVED** [review]
lgtm

**Comment by eck1001** [comment]
one more new IncomingStream(): 
https://github.com/medooze/media-server-node/blob/400f69d3069d2abb001a9bf74f000a2730966198/lib/EmulatedTransport.js#L77

**Comment by mildsunrise** [comment]
thanks! I'll amend the last commit with that. EmulatedTransport is still pending to apply typechecking on, so I did not notice

**Comment by mildsunrise** [comment]
actually, I'm pretty sure EmulatedTransport is broken and maybe we should just remove it rather than spend time replicating Transport#createIncomingStream into it. @murillo128

**Review by murillo128 — APPROVED** [review]
lgtm

**Comment by eck1001** [comment]
I'll let ya'll decide on how to handle `EmulatedTransport` but everything else looks good

**Pull request merged**
