### PR TITLE
Use share pointer for PlayerFacade and Player.js

### PR DESCRIPTION
**Pull request by ZitaLiao**

### CODE REVIEW

**Comment by ZitaLiao** [comment]
@murillo128 Do I need to include src/media-server_wrap.cxx in PR as well? There are other un-related space/line-length difference even though I used the same swig version (4.1.0)

**Comment by murillo128** [comment]
Can you make the change for audio as well? I will run swig after merging to avoid the whitespace changes

**Comment by murillo128** [comment]
@ZitaLiao  ptal

>Can you make the change for audio as well? I will run swig after merging to avoid the whitespace changes

**Comment by ZitaLiao** [comment]
> @ZitaLiao ptal
> 
> > Can you make the change for audio as well? I will run swig after merging to avoid the whitespace changes

@murillo128 added the audio as well. I compiled with swig on my env. Please check.

**Review by murillo128 — APPROVED** [review]

**Pull request merged**
