### PR TITLE
Started work on typescript annotations

### PR DESCRIPTION
**Pull request by maxhawkins**
I started writing typescript annotations for this project.

I'm not sure the package fits my specific use case anymore so I'm not sure I'll have a chance to finish them, but I thought I'd upload what I finished in case you want to support typescript / editor autocomplete.

### CODE REVIEW

**Comment by notedit** [comment]
cool,   I am glad to help.

**Comment by notedit** [comment]
we may better move semantic-sdp.d.ts to semantic-sdp repo.

**Comment by murillo128** [comment]
max, could you provide some feedback as why this project doesn't fit your
use case anymore?

would be helpful to understand what kind of features are missing.

**Comment by maxhawkins** [comment]
Sure! I'm looking for more control over playback of opus samples. I want to play back opus files through a PeerConnection in response to events.

I tried using the Player interface but I was having a hard time preparing my audio clips for playback. I could generate a hint track in ffmpeg but it didn't have the right format and segfaulted the program.

I might switch to the Go version which has a raw RTP interface. I stored audio clips in the rtpdump format when I was using Pion, so I might do that again with the Go wrapper.

**Comment by murillo128** [comment]
have you taken a look at the emulated transport object?

it allows to reply a pcap file which seems what you are looking for.

**Comment by maxhawkins** [comment]
I did try the emulated transport but wasn't able to map the SSRC in the pcap file to the SSRC in my offer. The pcap played but with the wrong SSRC. Maybe I was using it wrong?

**Comment by notedit** [comment]
@maxhawkins  I think streamer will be the right choice,  https://medooze.github.io/media-server-node/#streamer 

you can use ffmpeg/gstreamer send your opus file to a streamer.

**Comment by maxhawkins** [comment]
OK! I might end up finishing this after all. :-)

The streamer interface looks like a good fit. Thanks @notedit.

**Comment by notedit** [comment]
@murillo128 what's your opinion about types  support?   I think we better add support for it.
more and more people use typescript.

**Comment by maxhawkins** [comment]
Added the remaining media-server types. Still a few semantic-sdp types to go.

There might be some type errors as I'm just copy-pasting from the source.

**Comment by murillo128** [comment]
Re: typescript, seems that the definitions are quite self contained, so I wouldn't mind merging it.

My only problem is that I have not knowledge of ts, so i won't update it if there are any changes to the code, which may make the ts definition to be out of sync with the main code, so I would some help to support it in the future.

Would you mind moving the semantic-sdp to the corresponding repo? 

Re: RTPSession and Emulated transports, please open an issue or send a message to the mailing list so I can answer your questions there.

**Comment by notedit** [comment]
I would like to help with types defines update.

**Comment by murillo128** [comment]
@notedit thank you!

**Comment by maxhawkins** [comment]
I just pushed the finished type definitions. There may be some type errors or types I missed so please test against your own code. I'm using it on my server and everything seems to work ok!

**Comment by maxhawkins** [comment]
Unrelated question that came up while typing the API: What is a `TransactionManager`?

I see that `createPeerConnectionServer` takes one but there's no way to construct it from the javascript api.

**Comment by notedit** [comment]
@maxhawkins  see  https://github.com/medooze/transaction-manager

**Comment by murillo128** [comment]
thank you @maxhawkins !

Is there a way to move the semantic-sdp file to it's repo and reference it from here?

**Comment by murillo128** [comment]
hi @maxhawkins! we lost the CLAs signed in clahub, would you mind singing the following CLA for your contributions to the Medooze projects?

https://cla-assistant.io/medooze/clas

**Pull request merged**
