### PR TITLE
Updated media server

### PR DESCRIPTION
**Pull request by bcostdolby**

### CODE REVIEW

**Review by harryz2000 — APPROVED** [review]
lgtm

**Comment by mildsunrise** [comment]
I don't think we need pull requests to update the media server submodule, I'd consider it as pre-release steps and commit directly to master

**Comment by harryz2000** [comment]
No problem to me either. Just may need everyone be aware that we need to update all the six modules so they can have same media-server version.

**Comment by mildsunrise** [comment]
yeah, i tried to make that really clear in the release process document

**Pull request merged**
